version: "3"
services:
  nfs:
    image: nfs-centos    
    build: 
      context: ./nfs/
      dockerfile: ./Dockerfile
      #Args to build docker image, if change please build again
      args:
        #Shared Folder, which will be shared like a NFS Resources
        shared_folder: "/test-folder-nfs1 /test-folder-nfs2"
        #Shared IP, which can be access to NFS resources
        shared_ip: "192.168.1.24"
    privileged: true
    container_name: nfs-centos
    #Mapping volumes that will be become in shared folder
    volumes:
      - /tmp/test-folder-nfs1:/test-folder-nfs1
      - /tmp/test-folder-nfs2:/test-folder-nfs2
    ports:
      - "2049:2049"
      - "111:111/udp"
      - "111:111/tcp"
      - "20048:20048/udp"
      - "20048:20048/tcp"      
    restart: always
    command: >
      bash -c "exec /sbin/init && showmount -e 127.0.0.1 && sleep infinity"